name: Flutter Build APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - run: flutter pub get
      
      # Perintah ini akan memecah APK menjadi ukuran yang jauh lebih kecil
      - run: flutter build apk --release --split-per-abi
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          # Path diubah agar mengambil semua hasil split APK
          path: build/app/outputs/flutter-apk/*.apk